/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.4 */

#ifndef PB_PMS_PB_H_INCLUDED
#define PB_PMS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _PM {
    double PM1;
    double PM2;
    double PM10;
} PM;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define PM_init_default                          {0, 0, 0}
#define PM_init_zero                             {0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define PM_PM1_tag                               1
#define PM_PM2_tag                               2
#define PM_PM10_tag                              3

/* Struct field encoding specification for nanopb */
#define PM_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, DOUBLE,   PM1,               1) \
X(a, STATIC,   SINGULAR, DOUBLE,   PM2,               2) \
X(a, STATIC,   SINGULAR, DOUBLE,   PM10,              3)
#define PM_CALLBACK NULL
#define PM_DEFAULT NULL

extern const pb_msgdesc_t PM_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define PM_fields &PM_msg

/* Maximum encoded size of messages (where known) */
#define PM_size                                  27

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
